# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import data_pb2 as data__pb2


class UCPEDataStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetData = channel.unary_unary(
        '/data.UCPEData/GetData',
        request_serializer=data__pb2.DataRequest.SerializeToString,
        response_deserializer=data__pb2.DataResponse.FromString,
        )
    self.ModifyData = channel.unary_unary(
        '/data.UCPEData/ModifyData',
        request_serializer=data__pb2.DataRequest.SerializeToString,
        response_deserializer=data__pb2.DataChangeResponse.FromString,
        )


class UCPEDataServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetData(self, request, context):
    """test send data
    should handle: view/get images, memory, hugepages memory, cpus
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ModifyData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UCPEDataServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetData': grpc.unary_unary_rpc_method_handler(
          servicer.GetData,
          request_deserializer=data__pb2.DataRequest.FromString,
          response_serializer=data__pb2.DataResponse.SerializeToString,
      ),
      'ModifyData': grpc.unary_unary_rpc_method_handler(
          servicer.ModifyData,
          request_deserializer=data__pb2.DataRequest.FromString,
          response_serializer=data__pb2.DataChangeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'data.UCPEData', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
