# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\x12\x04\x64\x61ta\"\xab\x01\n\x0b\x44\x61taRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x13\n\x0bstr_request\x18\x02 \x01(\t\x12\x12\n\nstr_param1\x18\x03 \x01(\t\x12\x12\n\nstr_param2\x18\x04 \x01(\t\x12\x12\n\nstr_param3\x18\x05 \x01(\t\x12\x12\n\nstr_param4\x18\x06 \x01(\t\x12\x12\n\nstr_param5\x18\x07 \x01(\t\x12\x12\n\nstr_param6\x18\x08 \x01(\t\"b\n\x0c\x44\x61taResponse\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x14\n\x0cstr_response\x18\x02 \x01(\t\x12\x14\n\x0cint_response\x18\x03 \x01(\x05\x12\x16\n\x0e\x66loat_response\x18\x04 \x01(\x02\":\n\x12\x44\x61taChangeResponse\x12\x14\n\x0cstr_response\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2{\n\x08UCPEData\x12\x32\n\x07GetData\x12\x11.data.DataRequest\x1a\x12.data.DataResponse\"\x00\x12;\n\nModifyData\x12\x11.data.DataRequest\x1a\x18.data.DataChangeResponse\"\x00\x62\x06proto3')
)




_DATAREQUEST = _descriptor.Descriptor(
  name='DataRequest',
  full_name='data.DataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='data.DataRequest.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_request', full_name='data.DataRequest.str_request', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_param1', full_name='data.DataRequest.str_param1', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_param2', full_name='data.DataRequest.str_param2', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_param3', full_name='data.DataRequest.str_param3', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_param4', full_name='data.DataRequest.str_param4', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_param5', full_name='data.DataRequest.str_param5', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_param6', full_name='data.DataRequest.str_param6', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=192,
)


_DATARESPONSE = _descriptor.Descriptor(
  name='DataResponse',
  full_name='data.DataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='data.DataResponse.header', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_response', full_name='data.DataResponse.str_response', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_response', full_name='data.DataResponse.int_response', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_response', full_name='data.DataResponse.float_response', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=292,
)


_DATACHANGERESPONSE = _descriptor.Descriptor(
  name='DataChangeResponse',
  full_name='data.DataChangeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str_response', full_name='data.DataChangeResponse.str_response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='data.DataChangeResponse.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=352,
)

DESCRIPTOR.message_types_by_name['DataRequest'] = _DATAREQUEST
DESCRIPTOR.message_types_by_name['DataResponse'] = _DATARESPONSE
DESCRIPTOR.message_types_by_name['DataChangeResponse'] = _DATACHANGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataRequest = _reflection.GeneratedProtocolMessageType('DataRequest', (_message.Message,), dict(
  DESCRIPTOR = _DATAREQUEST,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:data.DataRequest)
  ))
_sym_db.RegisterMessage(DataRequest)

DataResponse = _reflection.GeneratedProtocolMessageType('DataResponse', (_message.Message,), dict(
  DESCRIPTOR = _DATARESPONSE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:data.DataResponse)
  ))
_sym_db.RegisterMessage(DataResponse)

DataChangeResponse = _reflection.GeneratedProtocolMessageType('DataChangeResponse', (_message.Message,), dict(
  DESCRIPTOR = _DATACHANGERESPONSE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:data.DataChangeResponse)
  ))
_sym_db.RegisterMessage(DataChangeResponse)



_UCPEDATA = _descriptor.ServiceDescriptor(
  name='UCPEData',
  full_name='data.UCPEData',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=354,
  serialized_end=477,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetData',
    full_name='data.UCPEData.GetData',
    index=0,
    containing_service=None,
    input_type=_DATAREQUEST,
    output_type=_DATARESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ModifyData',
    full_name='data.UCPEData.ModifyData',
    index=1,
    containing_service=None,
    input_type=_DATAREQUEST,
    output_type=_DATACHANGERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UCPEDATA)

DESCRIPTOR.services_by_name['UCPEData'] = _UCPEDATA

# @@protoc_insertion_point(module_scope)
