# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ucpe.libvirt_controller.grpc.libvirt_pb2 as libvirt__pb2


class LibvirtStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BlockPull = channel.unary_unary(
        '/Libvirt/BlockPull',
        request_serializer=libvirt__pb2.BlockPullRequest.SerializeToString,
        response_deserializer=libvirt__pb2.Response.FromString,
        )


class LibvirtServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def BlockPull(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LibvirtServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BlockPull': grpc.unary_unary_rpc_method_handler(
          servicer.BlockPull,
          request_deserializer=libvirt__pb2.BlockPullRequest.FromString,
          response_serializer=libvirt__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Libvirt', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
