# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autobcm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='autobcm.proto',
  package='autobcm',
  syntax='proto3',
  serialized_options=_b('\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\rautobcm.proto\x12\x07\x61utobcm\"9\n\rConfigRequest\x12\x0e\n\x06vlanid\x18\x01 \x01(\x05\x12\x0b\n\x03pbm\x18\x02 \x01(\t\x12\x0b\n\x03ubm\x18\x03 \x01(\t\"\x1e\n\x0b\x43onfigReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xfb\x03\n\x07\x41utoBCM\x12\x41\n\x0fShowActivePorts\x12\x16.autobcm.ConfigRequest\x1a\x14.autobcm.ConfigReply\"\x00\x12<\n\nCreateVLAN\x12\x16.autobcm.ConfigRequest\x1a\x14.autobcm.ConfigReply\"\x00\x12:\n\x08\x41\x64\x64Ports\x12\x16.autobcm.ConfigRequest\x1a\x14.autobcm.ConfigReply\"\x00\x12:\n\x08SetPVLAN\x12\x16.autobcm.ConfigRequest\x1a\x14.autobcm.ConfigReply\"\x00\x12;\n\tShowVLANs\x12\x16.autobcm.ConfigRequest\x1a\x14.autobcm.ConfigReply\"\x00\x12=\n\x0b\x44\x65stroyVLAN\x12\x16.autobcm.ConfigRequest\x1a\x14.autobcm.ConfigReply\"\x00\x12=\n\x0bRemovePorts\x12\x16.autobcm.ConfigRequest\x1a\x14.autobcm.ConfigReply\"\x00\x12<\n\nShowPVLANs\x12\x16.autobcm.ConfigRequest\x1a\x14.autobcm.ConfigReply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_CONFIGREQUEST = _descriptor.Descriptor(
  name='ConfigRequest',
  full_name='autobcm.ConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vlanid', full_name='autobcm.ConfigRequest.vlanid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pbm', full_name='autobcm.ConfigRequest.pbm', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ubm', full_name='autobcm.ConfigRequest.ubm', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=83,
)


_CONFIGREPLY = _descriptor.Descriptor(
  name='ConfigReply',
  full_name='autobcm.ConfigReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='autobcm.ConfigReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['ConfigRequest'] = _CONFIGREQUEST
DESCRIPTOR.message_types_by_name['ConfigReply'] = _CONFIGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigRequest = _reflection.GeneratedProtocolMessageType('ConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGREQUEST,
  '__module__' : 'autobcm_pb2'
  # @@protoc_insertion_point(class_scope:autobcm.ConfigRequest)
  })
_sym_db.RegisterMessage(ConfigRequest)

ConfigReply = _reflection.GeneratedProtocolMessageType('ConfigReply', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGREPLY,
  '__module__' : 'autobcm_pb2'
  # @@protoc_insertion_point(class_scope:autobcm.ConfigReply)
  })
_sym_db.RegisterMessage(ConfigReply)


DESCRIPTOR._options = None

_AUTOBCM = _descriptor.ServiceDescriptor(
  name='AutoBCM',
  full_name='autobcm.AutoBCM',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=118,
  serialized_end=625,
  methods=[
  _descriptor.MethodDescriptor(
    name='ShowActivePorts',
    full_name='autobcm.AutoBCM.ShowActivePorts',
    index=0,
    containing_service=None,
    input_type=_CONFIGREQUEST,
    output_type=_CONFIGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateVLAN',
    full_name='autobcm.AutoBCM.CreateVLAN',
    index=1,
    containing_service=None,
    input_type=_CONFIGREQUEST,
    output_type=_CONFIGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddPorts',
    full_name='autobcm.AutoBCM.AddPorts',
    index=2,
    containing_service=None,
    input_type=_CONFIGREQUEST,
    output_type=_CONFIGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetPVLAN',
    full_name='autobcm.AutoBCM.SetPVLAN',
    index=3,
    containing_service=None,
    input_type=_CONFIGREQUEST,
    output_type=_CONFIGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ShowVLANs',
    full_name='autobcm.AutoBCM.ShowVLANs',
    index=4,
    containing_service=None,
    input_type=_CONFIGREQUEST,
    output_type=_CONFIGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DestroyVLAN',
    full_name='autobcm.AutoBCM.DestroyVLAN',
    index=5,
    containing_service=None,
    input_type=_CONFIGREQUEST,
    output_type=_CONFIGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemovePorts',
    full_name='autobcm.AutoBCM.RemovePorts',
    index=6,
    containing_service=None,
    input_type=_CONFIGREQUEST,
    output_type=_CONFIGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ShowPVLANs',
    full_name='autobcm.AutoBCM.ShowPVLANs',
    index=7,
    containing_service=None,
    input_type=_CONFIGREQUEST,
    output_type=_CONFIGREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTOBCM)

DESCRIPTOR.services_by_name['AutoBCM'] = _AUTOBCM

# @@protoc_insertion_point(module_scope)
